using ClockiFyAMS.Database;
using System;
using System.Data;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;

using IronPython.Hosting;
using Microsoft.Scripting;
using Microsoft.Scripting.Hosting;
using System.Windows.Forms.VisualStyles;

namespace ClockiFyAMS.Modals
{
    /// <summary>
    /// Interaction logic for Records.xaml
    /// </summary>
    public partial class Records : UserControl
    {
        private MainWindow root;
        public Records(MainWindow root)
        {
            InitializeComponent();
            this.root = root;
            dtp.Text = DateTime.Now.ToString("yyyy-MM-dd");
            LoadData();
        }

        private async void launchQr_Click(object sender, RoutedEventArgs e)
        {
            launchQR();

            //var dialogBox
            //              = new DialogModal(
            //              "Function Under Construction",
            //              PackIconKind.AccountHardHat,
            //              MessageType.Info);

            //object result = await DialogHost.Show(dialogBox, "RootDialogHostId");
            //if (!(result is null))
            //{
            //    //if ((string)result == "cmd1execute") Application.Current.Shutdown();
            //}
            //process.StartInfo.FileName = @"C:\Python310\python.exe";
            //process.StartInfo.RedirectStandardInput = true;

            //process.StartInfo.CreateNoWindow = false;
            //process.StartInfo.UseShellExecute = false;
            //process.StartInfo.Arguments = AppDomain.CurrentDomain.BaseDirectory + @"QRScanner\main.py";
            //process.Start();
        }

        void launchQR()
        {

            //ProcessStartInfo start = new ProcessStartInfo();
            //start.FileName = "python.exe";
            //start.Arguments = AppDomain.CurrentDomain.BaseDirectory + @"QRScanner\main.py";
            //start.UseShellExecute = false;// Do not use OS shell
            //start.CreateNoWindow = true; // We don't need new window
            //start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            //start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            //Process p = Process.Start(start);
            //p.Start();

            var engine = Python.CreateEngine();
            var searchPaths = engine.GetSearchPaths();
            searchPaths.Add(@"\QRScanner\");
            engine.SetSearchPaths(searchPaths);

            var scope = engine.CreateScope();
            var source = engine.CreateScriptSourceFromFile(@"QRScanner\main.py");
            var compilation = source.Compile();
            compilation.Execute(scope);

        }

        private void btnDelete_Click(object sender, RoutedEventArgs e)
        {
            var wr = (Attendance)dgvPresentEnt.SelectedItem;
            config.AttObj = wr;
            new Delete().RemoveRecord();
            dgvPresentEnt.Items.Remove(dgvPresentEnt.SelectedItem);
        }
        void LoadData()
        {
            dgvPresentEnt.Items.Clear();
            DataTable dt = new Read().LoadLogs();
            if (dt.Rows.Count > 0)
            {
                foreach (DataRow dr in dt.Rows)
                {
                    var att = new Attendance
                    {
                        UID = (string)dr["UID"],
                        FullName = (string)dr["FullName"],
                        AttDate = (DateTime.Parse((string)dr["Date"])).ToString("yyyy-MM-dd"),
                        TimeIn = (string)dr["TimeIn"],
                        Timeout = (string)dr["TimeOut"],
                        TImeWorked = (string)dr["TimeWorked"]
                    };

                    dgvPresentEnt.Items.Add(att);
                }
            }
        }

        private void filter_Click(object sender, RoutedEventArgs e)
        {
            config.key = DateTime.Parse(dtp.Text).ToString("yyyy-MM-dd");
            LoadData();
        }

        private void refresh_Click(object sender, RoutedEventArgs e)
        {
            LoadData();
        }
    }

}
